name: Backend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r starter/backend/requirements.txt

      - name: Run pytest
        run: pytest starter/backend

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: |
          docker build -t backend-ci-build starter/backend
